"""Confidence scoring (fusion) and transparency-label mapping.

Signal B (the semantic LLM judge) is the PRIMARY detector; Signal A (stylometric)
is a cheap secondary corroborator. We learned empirically that Signal A is blind
to fluent AI (README finding), so we do NOT treat the two as equal peers — a
symmetric disagreement penalty would let a blind Signal A veto a correct Signal B.

Fusion (combine into one confidence in [0,1], 1 = AI):
  1. weighted base:  raw = 0.2*A + 0.8*B   (B dominates; A nudges)
  2. length cap:     confidence = 0.5 + (raw-0.5) * min(1, words/40)
If Signal B is unavailable we fall back to A alone AND halve confidence strength,
since our primary detector is gone.

Protection against false accusations now comes from B's quality (it also reliably
recognizes genuine humans), not from an extreme threshold.

Thresholds:
  confidence >= 0.75  -> ai
  confidence <  0.25  -> human
  otherwise           -> uncertain
"""

# --- weights / thresholds (single source of truth) ---
_W_A = 0.2
_W_B = 0.8
AI_THRESHOLD = 0.75
HUMAN_THRESHOLD = 0.25
_LENGTH_FULL_CONF_WORDS = 40


def _clamp(x):
    return max(0.0, min(1.0, x))


def fuse(score_a, score_b, word_count, b_available=True):
    """Combine the two signal scores into one confidence in [0,1] (1 = AI)."""
    if b_available:
        raw = _W_A * score_a + _W_B * score_b   # Signal B dominates
        strength = 1.0
    else:
        # Primary signal (B) gone: fall back to the weak secondary signal alone
        # and damp confidence, so results lean uncertain rather than overconfident.
        raw = score_a
        strength = 0.5

    length_conf = min(1.0, word_count / _LENGTH_FULL_CONF_WORDS)
    confidence = 0.5 + (raw - 0.5) * length_conf * strength
    return round(_clamp(confidence), 3)


# --- transparency labels (verbatim text the reader sees) ---

def _ai_label(pct):
    return (
        f"⚠️ This content appears to be AI-generated. Our system analyzed its "
        f"writing patterns and is highly confident (about {pct}%) it was produced "
        f"by an AI tool rather than written by a person. This is an automated "
        f"assessment, not a verdict — the creator can contest it."
    )


def _human_label(pct):
    return (
        f"✓ This content appears to be human-written. Our system found writing "
        f"patterns consistent with a human author and is confident (about {pct}%) "
        f"it was not AI-generated."
    )


_UNCERTAIN_LABEL = (
    "❓ We couldn't confidently determine how this content was created. Our system "
    "found mixed signals — it may have been written by a person, generated by AI, "
    "or a mix of both. We're showing this note instead of a definitive label to "
    "avoid making a wrong call."
)


def to_label(confidence):
    """Map a confidence score to {classification, label} using the thresholds."""
    if confidence >= AI_THRESHOLD:
        pct = round(confidence * 100)
        return {"classification": "ai", "label": _ai_label(pct)}
    if confidence < HUMAN_THRESHOLD:
        pct = round((1.0 - confidence) * 100)
        return {"classification": "human", "label": _human_label(pct)}
    return {"classification": "uncertain", "label": _UNCERTAIN_LABEL}
