"""M5 verification — transparency labels + appeals workflow.

Run directly: `python verify_m5.py`. Exits non-zero on any failure.

Checks two things against planning.md:
  1. to_label() produces all three EXACT label strings (§3 Transparency labels)
     at the right thresholds (§2), with correct {pct} interpolation.
  2. POST /appeal round-trips: submit -> appeal -> status flips to under_review,
     original verdict preserved, reason visible in GET /log?status=under_review,
     and 404 on an unknown content_id.
"""

import app as app_module
from scoring import to_label

# --- Exact label text, copied verbatim from planning.md §3 ------------------
# {pct} placeholders are filled the same way the spec defines them.
AI_TEXT = (
    "⚠️ This content appears to be AI-generated. Our system analyzed its writing "
    "patterns and is highly confident (about {pct}%) it was produced by an AI "
    "tool rather than written by a person. This is an automated assessment, not "
    "a verdict — the creator can contest it."
)
HUMAN_TEXT = (
    "✓ This content appears to be human-written. Our system found writing "
    "patterns consistent with a human author and is confident (about {pct}%) it "
    "was not AI-generated."
)
UNCERTAIN_TEXT = (
    "❓ We couldn't confidently determine how this content was created. Our system "
    "found mixed signals — it may have been written by a person, generated by AI, "
    "or a mix of both. We're showing this note instead of a definitive label to "
    "avoid making a wrong call."
)

_failures = []


def check(name, ok, detail=""):
    mark = "PASS" if ok else "FAIL"
    print(f"  [{mark}] {name}" + (f" — {detail}" if detail and not ok else ""))
    if not ok:
        _failures.append(name)


def verify_labels():
    print("1. Label variants (exact text + thresholds)")

    # High-confidence AI: 0.95 -> pct = round(95) = 95
    ai = to_label(0.95)
    check("0.95 -> classification 'ai'", ai["classification"] == "ai", ai["classification"])
    check("AI label text matches spec verbatim", ai["label"] == AI_TEXT.format(pct=95))

    # High-confidence human: 0.10 -> pct = round((1-0.10)*100) = 90
    hu = to_label(0.10)
    check("0.10 -> classification 'human'", hu["classification"] == "human", hu["classification"])
    check("human label text matches spec verbatim", hu["label"] == HUMAN_TEXT.format(pct=90))

    # Uncertain: 0.50 -> no percentage in text
    un = to_label(0.50)
    check("0.50 -> classification 'uncertain'", un["classification"] == "uncertain", un["classification"])
    check("uncertain label text matches spec verbatim", un["label"] == UNCERTAIN_TEXT)
    check("uncertain label shows NO percentage", "%" not in un["label"])

    # Threshold boundaries (§2 table: AI >= 0.75, human < 0.25)
    check("0.75 is AI (boundary inclusive)", to_label(0.75)["classification"] == "ai")
    check("0.749 is uncertain (just under AI bar)", to_label(0.749)["classification"] == "uncertain")
    check("0.25 is uncertain (human bar exclusive)", to_label(0.25)["classification"] == "uncertain")
    check("0.249 is human", to_label(0.249)["classification"] == "human")


def verify_appeal():
    print("2. Appeal round-trip")
    # Redirect the audit log to a throwaway file so this test doesn't pollute
    # the real audit_log.jsonl.
    import audit
    audit._LOG_PATH = "/private/tmp/claude-501/-Users-matthew-Dev-AI201Project4ProvenanceGuard/c72a3ee6-a69b-4bf7-823b-ea6165832fe0/scratchpad/verify_audit.jsonl"

    client = app_module.app.test_client()

    # Submit a piece of content to get a real content_id + original verdict.
    sub = client.post("/submit", json={"text": "word " * 60, "creator_id": "mara"})
    check("submit returns 200", sub.status_code == 200, str(sub.status_code))
    body = sub.get_json()
    cid = body["content_id"]
    original_attr = body["attribution"]
    original_conf = body["confidence"]

    # Appeal it (using the assignment's field name `creator_reasoning`).
    reasoning = "I wrote this myself, here are my drafts."
    ap = client.post("/appeal", json={"content_id": cid, "creator_reasoning": reasoning})
    check("appeal returns 200", ap.status_code == 200, str(ap.status_code))
    resp = ap.get_json()
    check("response confirms appeal received", "message" in resp and "received" in resp["message"].lower())
    rec = resp["record"]

    check("status flipped to under_review", rec.get("status") == "under_review", rec.get("status"))
    check("original attribution preserved", rec.get("attribution") == original_attr)
    check("original confidence preserved", rec.get("confidence") == original_conf)
    check("appeal.creator_reasoning stored verbatim",
          rec.get("appeal", {}).get("creator_reasoning") == reasoning)
    check("appeal.submitted_at present", bool(rec.get("appeal", {}).get("submitted_at")))

    # Appeal queue: GET /log?status=under_review must surface it with the reasoning.
    q = client.get("/log?status=under_review").get_json()["entries"]
    match = next((e for e in q if e["content_id"] == cid), None)
    check("record appears in appeal queue", match is not None)
    check("reasoning visible to human reviewer",
          match and match["appeal"]["creator_reasoning"] == reasoning)

    # GET /content/{id} returns the same updated record.
    got = client.get(f"/content/{cid}").get_json()
    check("GET /content/{id} reflects under_review", got.get("status") == "under_review")

    # 404 on unknown content_id.
    miss = client.post("/appeal", json={"content_id": "c_doesnotexist", "creator_reasoning": "x"})
    check("404 on unknown content_id", miss.status_code == 404, str(miss.status_code))

    # 400 on missing creator_reasoning.
    bad = client.post("/appeal", json={"content_id": cid})
    check("400 on missing creator_reasoning", bad.status_code == 400, str(bad.status_code))

    # `reason` still accepted as a backward-compatible alias.
    alias = client.post("/appeal", json={"content_id": cid, "reason": "alias works"})
    check("`reason` alias still accepted", alias.status_code == 200, str(alias.status_code))


def verify_endpoint_variants():
    """Prove the label returned by POST /submit CHANGES with confidence — all
    three variants reachable end-to-end, not the same text regardless of score.

    Signal B depends on the Groq API (non-deterministic), so we drive the two
    signal functions to controlled scores that land confidence in each band.
    """
    print("3. /submit returns a different label per confidence band")
    import audit
    audit._LOG_PATH = "/private/tmp/claude-501/-Users-matthew-Dev-AI201Project4ProvenanceGuard/c72a3ee6-a69b-4bf7-823b-ea6165832fe0/scratchpad/verify_audit.jsonl"
    client = app_module.app.test_client()

    orig_styl = app_module.stylometric_score
    orig_llm = app_module.llm_judge_score
    long_text = "word " * 60  # 60 words -> length cap doesn't damp the score

    # (label A, label B) drive raw = 0.2*A + 0.8*B into each band.
    bands = {
        "ai": (0.90, 0.95),        # raw 0.94 -> AI  (>= 0.75)
        "human": (0.05, 0.05),     # raw 0.05 -> human (< 0.25)
        "uncertain": (0.50, 0.50),  # raw 0.50 -> uncertain
    }
    seen_labels = {}
    try:
        for expected, (a, b) in bands.items():
            app_module.stylometric_score = lambda t, _a=a: {"score": _a, "detail": "stub"}
            app_module.llm_judge_score = lambda t, _b=b: {
                "score": _b, "rationale": "stub", "available": True
            }
            resp = client.post("/submit", json={"text": long_text, "creator_id": "u"}).get_json()
            check(f"{expected} band -> attribution '{expected}'",
                  resp["attribution"] == expected, resp["attribution"])
            seen_labels[expected] = resp["label"]
    finally:
        app_module.stylometric_score = orig_styl
        app_module.llm_judge_score = orig_llm

    check("all three label strings are distinct", len(set(seen_labels.values())) == 3)
    check("AI label came back from /submit", seen_labels.get("ai", "").startswith("⚠️"))
    check("human label came back from /submit", seen_labels.get("human", "").startswith("✓"))
    check("uncertain label came back from /submit", seen_labels.get("uncertain", "").startswith("❓"))


if __name__ == "__main__":
    verify_labels()
    verify_appeal()
    verify_endpoint_variants()
    print()
    if _failures:
        print(f"{len(_failures)} FAILED: {_failures}")
        raise SystemExit(1)
    print("All checks passed.")
